# Project: maze-runner
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Camera.o Entity.o Config.o Coin.o Ghost.o Key.o Environment.o
LINKOBJ  = main.o Camera.o Entity.o Config.o Coin.o Ghost.o Key.o Environment.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -mwindows -lglut32 -lglu32 -lopengl32 -lwinmm -lgdi32
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"../include/shared" -I"../include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++" -I"../include/shared" -I"../include"
BIN      = maze-runner.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) -DGLUT_STATIC
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

src/main.o: main.cpp
	$(CPP) -c main.cpp -o ../src/main.o $(CXXFLAGS)

src/Camera.o: Camera.cpp
	$(CPP) -c Camera.cpp -o ../src/Camera.o $(CXXFLAGS)

src/Entity.o: Entity.cpp
	$(CPP) -c Entity.cpp -o ../src/Entity.o $(CXXFLAGS)

src/Config.o: Config.cpp
	$(CPP) -c Config.cpp -o ../src/Config.o $(CXXFLAGS)

src/Coin.o: Coin.cpp
	$(CPP) -c Coin.cpp -o ../src/Coin.o $(CXXFLAGS)

src/Ghost.o: Ghost.cpp
	$(CPP) -c Ghost.cpp -o ../src/Ghost.o $(CXXFLAGS)

src/Key.o: Key.cpp
	$(CPP) -c Key.cpp -o ../src/Key.o $(CXXFLAGS)

src/Environment.o: Environment.cpp
	$(CPP) -c Environment.cpp -o ../src/Environment.o $(CXXFLAGS)
