# Project: maze-runner
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Camera.o Config.o Entity.o main.o entity/Coin.o entity/Ghost.o entity/Key.o environment/Environment.o
LINKOBJ  = Camera.o Config.o Entity.o main.o entity/Coin.o entity/Ghost.o entity/Key.o environment/Environment.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -lopengl32 -lglu32 -lglut32
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/Users/muhffikkri/Downloads/maze-runner-main/maze-runner-main/include" -I"D:/kuliah/semester4/gti/maze-runner/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++" -I"C:/Users/muhffikkri/Downloads/maze-runner-main/maze-runner-main/include" -I"D:/kuliah/semester4/gti/maze-runner/include"
BIN      = maze-runner.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Camera.o: Camera.cpp
	$(CPP) -c Camera.cpp -o Camera.o $(CXXFLAGS)

Config.o: Config.cpp
	$(CPP) -c Config.cpp -o Config.o $(CXXFLAGS)

Entity.o: Entity.cpp
	$(CPP) -c Entity.cpp -o Entity.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

entity/Coin.o: entity/Coin.cpp
	$(CPP) -c entity/Coin.cpp -o entity/Coin.o $(CXXFLAGS)

entity/Ghost.o: entity/Ghost.cpp
	$(CPP) -c entity/Ghost.cpp -o entity/Ghost.o $(CXXFLAGS)

entity/Key.o: entity/Key.cpp
	$(CPP) -c entity/Key.cpp -o entity/Key.o $(CXXFLAGS)

environment/Environment.o: environment/Environment.cpp
	$(CPP) -c environment/Environment.cpp -o environment/Environment.o $(CXXFLAGS)
